// ============================================
// GAME CONFIGURATION
// ============================================
export const CONFIG = {
  CANVAS_WIDTH: 800,
  CANVAS_HEIGHT: 600,
  PLAYER_SPEED: 0.75,
  ENEMY_SPEED: 0.375,
  BULLET_SPEED: 2,
  PLAYER_SHOOT_COOLDOWN: 200,
  ENEMY_SHOOT_COOLDOWN: 1500,
  PLAYER_MAX_HEALTH: 100,
  ENEMY_MAX_HEALTH: 50,
  PLAYER_DAMAGE_FROM_ENEMY: 20,
  ENEMY_DAMAGE_FROM_PLAYER: 35,
  GRID_SIZE: 50,

  // Boss Config
  BOSS_WAVE_INTERVAL: 5,
  BOSS_MAX_HEALTH: 300,
  BOSS_SPEED: 0.25,
  BOSS_SHOOT_COOLDOWN: 600,
  BOSS_WIDTH: 72,
  BOSS_HEIGHT: 56,
  BOSS_DAMAGE_PER_BULLET: 15,
  MAX_ENEMY_BULLETS: 50,

  // Shield Ability
  SHIELD_ABILITY_DURATION: 1200, // 0.8 seconds
  SHIELD_ABILITY_COOLDOWN: 5000, // 5 seconds
};
